### ISSUE TITLE
[Traefik Pilot] Traefik Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [mrdrelar/traefik-plugin-rewriteheader#1]
The plugin was not imported into Traefik Pilot.

Cause:
```
failed to run with Yaegi: plugin: failed to eval CreateConfig: 1:28: undefined: traefik_plugin_rewriteheader
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.containo.us/).

**Comment by mrdrelar** [comment]
Fixed in this [commit](https://github.com/mrdrelar/traefik-plugin-rewriteheader/commit/b7b351a967e94b2aa1a61b8f9a26290383923eae)
